### IDs:
Insert yours IDs to the cell below

ID #1: 203972922

ID #2: 201312907 


## Read the following instructions carefully:

1. This jupyter notebook contains all the step by step instructions needed for this exercise.
1. You are free to add cells.
1. Write your functions and your answers in this jupyter notebook only.
1. Answers to theoretical questions should be written in **markdown cells (with $\LaTeX$ support)**.
1. Submit this jupyter notebook only using your ID as a filename. Not to use ZIP or RAR. For example, your Moodle submission file name should look like this (two id numbers): `123456789_987654321.ipynb`.

### Question 1 - Defective products

In a manufacturing pipeline products are 3% defective. We are interested in examining a defective product to see what goes wrong on the belt. We need to ask the facility manager to send us a set of independent samples for examination.

#### 1.A

How many independent samples should we ask for in order to have a 85% probability of having at least one defective product in the batch sent? You should write a function.

## Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import scipy
from scipy.stats import binom


##  Answer:
* because the sampels are independent we can say that:
    * $$ T = \sum_{k=0}^n{X_{k}}   $$ 
    * $$ P(T) = p^n $$
* 
<br> $$ P_{almost-1-defect}= P(n>=1) = 1-P(n<1) = 1- P_{not-defect}^N$$<br>
<br> $$  P_{not-defect}^N = 1-P_{almost-1-defect} $$ <br>
<br> $$ log_{not-defect}(1-P_{almost-1-defect}) = N $$ <br>



In [ ]:
# we want to define new randum variable as the sum of N variable and use the fact that they are independent
def calculate_the_amount_of_independent_samples_2_get_almost_one_defect(goal_probability, defect_prob):
    prob_2_not_achieve_defect = 1-goal_probability
    non_defect_prob = 1-defect_prob
    amount_of_independent_samples = int(math.ceil((math.log(prob_2_not_achieve_defect, non_defect_prob))))
    print('The amount of independent samples is '+ str(amount_of_independent_samples))

In [ ]:
# initial info 
defect_prob = 0.03
goal_probability = 0.85
min_amount_of_defect = 1

calculate_the_amount_of_independent_samples_2_get_almost_one_defect(goal_probability, defect_prob)

## The sums of independent variable set as:



#### 1.B
Answer this part again with the following changes: products are 4% defective and we want a 95% probability of at least one defective product in the batch.

In [ ]:
# initial info 
defect_prob = 0.04
goal_probability = 0.95
min_amount_of_defect = 1
calculate_the_amount_of_independent_samples_2_get_almost_one_defect(goal_probability, defect_prob)


#### 1.C 

Consider the following cases and calculate how many independent samples are required: 

1. Products are 10% defective and we want a 90% probability of at least 5 defective products in the batch.
1. Products are 30% defective and we want a 90% probability of at least 15 defective products in the batch.

Explain the difference between the two results. You should use mathematical reasoning based on the properties of distributions you saw in class and visualizations in your answer.

## First  Case:
* Products are 10% defective and we want a 90% probability of at least 5 defective products in the batch

<br> $$ P_{almost-5-defect}= P(n>=k) = 1-P(n<k) = 1- \sum_{k=1}^{k-1}B(n,k,p) $$<br>


In [ ]:
def evaluate_the_amount_of_independent_samples_2_get_almost_k_defects(desire_amount_of_defect, defect_prob, goal_probability):
    # reset amount independet variables
    num_of_samples = 1
    list_of_probability = []
    list_of_amount_of_independent_sampels = []
    while True:
        
        p = 1 - sum([binom.pmf(number_of_defects, num_of_samples, defect_prob) for number_of_defects in range(desire_amount_of_defect)])
        
        # vallidate if achieve the desire prob'
        list_of_probability.append(p)
        list_of_amount_of_independent_sampels.append(num_of_samples)
        if p >= goal_probability:
            break
        else:
            # increase the amout of sampels
            num_of_samples+=1
            continue
    print('The amount of independent samples is '+str(num_of_samples))
    return list_of_probability, list_of_amount_of_independent_sampels


In [ ]:
# initial info 

defect_prob = 0.1
goal_probability = 0.9
desire_amount_of_defect = 5    
dumm,dumm123 = evaluate_the_amount_of_independent_samples_2_get_almost_k_defects(desire_amount_of_defect, defect_prob,goal_probability)

## Secound  Case:
* Products are 30% defective and we want a 90% probability of at least 15 defective products in the batch

In [ ]:
# initial info 
defect_prob = 0.3
goal_probability = 0.9
desire_amount_of_defect = 15
dumm,dumm123 = evaluate_the_amount_of_independent_samples_2_get_almost_k_defects(desire_amount_of_defect, defect_prob,goal_probability)

## Explaination 
* the difference between the two results are:
    * math
    * math

In [ ]:
defect_prob = 0.1
goal_probability = 0.9
desire_amount_of_defect = 5  
x1,y1 = evaluate_the_amount_of_independent_samples_2_get_almost_k_defects(desire_amount_of_defect, defect_prob, 1)
defect_prob = 0.3
goal_probability = 0.9
desire_amount_of_defect = 15
x2,y2 = evaluate_the_amount_of_independent_samples_2_get_almost_k_defects(desire_amount_of_defect, defect_prob, 1)
plt.close()

plt.plot(y1, x1, '--', 'g', label='Case1')
plt.plot(y2, x2, ':', 'b', label='Case2')
plt.grid()
plt.title('The amount of sampels as function of the probability')
plt.ylabel('Probability')
plt.xlabel('# Samples')
plt.legend()
plt.xlim(0,100)



### Question 2 - Rent distributions in Randomistan

The state of Randomistan conducted a survey to study the distribution of rent paid in two neighboring towns, Stochastic Heights and Random Grove, to be denoted SH and RG.<br> 

Here are some findings of the survey:
* The population of SH and RG is 16,000 and 22,000 respectively. <br>
* The mean rent in SH and RG is 6300RCU and 4200RCU respectively.
* The median rent is 4600RCU in both towns.
* The IQR of the rent is smaller in SH than in RG.

All data generated in this question needs to be consistent with these findings.

#### 2.A
Draw histograms that describe 2 different scenarii of possible distributions of rent in the two towns.Your histograms should:<br>
* Use bins of 100RCU each.
* Have at least 10 non zero bins.

In [ ]:
population_sh = 16e3
population_rg  = 22e3
mean_sh = 16e3
mean_rg  = 22e3
median_rent = 46e2

bins_size = 100 # needs to verify that there are at least 10 non zeros points 




#### 2.B
Draw a histogram of a third scenario with the same properties. <br>
In addition, in this scenario the rent in SH should have a higher variance than the rent in RG.

The survey also examined the per household income (PHI) in these two places.<br>

It found that:<br>
* The mean of PHI in SH is 12500 and in RG is 8500.
* The median is 12000 in SH and 8000 in RG.
* The covariance of the rent and the PHI was observed to be as in the formula below with $\alpha=97\%$ and $\alpha=89\%$ in SH and in RG respectively.<br><br>
$$Cov(rent, PHI) = \alpha * \sqrt{Var(rent)} * \sqrt{Var(PHI)}$$

#### 2.C
Produce rent and PHI data for the two cities, that is consistent with these findings. The covariances in your data can deviate by up to 1% from the numbers given $\alpha$.

In [ ]:
mean_ph = 125e2
mean_sh  = 85e2
median_ph = 12e3
median_sh  = 8e3
alpha_rate = [0.89,0.97]
covariances_deviate_percent = 0.01




#### 2.D
Produce two heatmaps that describe these two bivariate joint distributions. Make sure you carefully consider the selected binning resolution.

### Question 3 - Multinomial Distributions

1. Let $X \sim Multinomial(n,\vec{p})$ be a multinomial random variable where $n=20$ and $\vec{p} = (0.2,  0.1,  0.1,  0.1,  0.2,  0.3)$. Note that X is a vector of counts.


2. Let $Y = X_2 + X_3 + X_4$ be a random variable.


3. Create $k=100$ experiments where $X$ is sampled using Python. Calculate the empirical centralized third moment of $Y$ based on your $k$ experiments.


4. Compare your result to the calculation in class for the centralized third moment of the **binomial** distribution and explain your observation.

In [3]:
# !pip install scipy
# !pip3 install scipy
import sys
!{sys.executable} -m pip install scipy

     |████████████████████████████████| 33.2 MB 1.9 MB/s            


In [9]:
k = 100
n = 20
p = [0.2,0.1,0.1,0.1,0.2,0.3]
print(f'size of X vector is {len(p)}')

experiments = 10  #should be 100

#TODO: LESADER LATER
import numpy as np
experiments_vector = np.random.multinomial(n=n, pvals=p, size=experiments)
print(f'experiments_vector is:\n {experiments_vector}')

#SHAKUL
import pandas as pd
df = pd.DataFrame(experiments_vector, columns=['X1','X2','X3','X4','X5','X6'])
print(f'\ndf.head() is:\n{df.head(10)}')

df['Y'] = df['X2'] + df['X3'] + df['X4']
df.drop(columns=['X1','X5','X6'], inplace=True)
print(f'\ndf.head() with Y is:\n{df.head(10)}')

Y = df['Y'].tolist()
print(f'\nY is:\n{Y}')

from scipy.stats import moment
result = moment(Y, moment=3)
print(f'\nresult {result}')

# from scipy.stats import multinomial
# rv = multinomial(n=n, p=p)



size of X vector is 6
experiments_vector is:
 [[8 1 1 0 3 7]
 [7 6 0 0 4 3]
 [3 5 0 5 3 4]
 [6 1 2 3 1 7]
 [7 0 3 2 1 7]
 [2 5 1 0 4 8]
 [6 3 3 1 3 4]
 [8 1 2 0 5 4]
 [6 2 0 2 7 3]
 [2 6 1 1 6 4]]

df.head() is:
   X1  X2  X3  X4  X5  X6
0   8   1   1   0   3   7
1   7   6   0   0   4   3
2   3   5   0   5   3   4
3   6   1   2   3   1   7
4   7   0   3   2   1   7
5   2   5   1   0   4   8
6   6   3   3   1   3   4
7   8   1   2   0   5   4
8   6   2   0   2   7   3
9   2   6   1   1   6   4

df.head() with Y is:
   X2  X3  X4   Y
0   1   1   0   2
1   6   0   0   6
2   5   0   5  10
3   1   2   3   6
4   0   3   2   5
5   5   1   0   6
6   3   3   1   7
7   1   2   0   3
8   2   0   2   4
9   6   1   1   8

Y is:
[2, 6, 10, 6, 5, 6, 7, 3, 4, 8]

result 1.8359999999999979


### Question 4 - Covariance and independence

What is the variance of the sum X +Y + Z of three random variables in terms of the variances of X, Y and Z and the covariances between each pair of random variables? What happens if X,Y,Z are pairwise independent? If X,Y,Z are pairwise independent, are they necessarily collectively independent? Prove your answer.

In [ ]:
see end of lecture 3

### Question 5 - Convolutions

#### 5.A
Write a program, `Q = NFoldConv(P , n)`, that takes as input:
* A distribution, P, of a random variable that takes finitely many integer values
* An integer n

and produces the distribution, Q, of the sum of n independent repeats of random variables, each of which has the distribution P.

#### 5.B
Compute the distribution of the sum of the results of rolling a fair octahedron 17 times.

<img src="https://upload.wikimedia.org/wikipedia/commons/2/27/Octahedron.jpg" width="200">
